---
title: "Bankruptcy of Pacific Gas and Electric"
output: html_document
---

```{r}
pge<-read.csv("PGEmonthly9821.txt")
attach(pge)
head(pge)
```
```{r}
plot(ts(Return,start=c(1998,1),freq=12),ylab="PGE Return", main="PGE Monthly Returns, 1998 to 2021")
```
```{r}
plot(ts(Price,start=c(1998,1),freq=12),ylab="PGE Price", main="PGE Monthly Closing Price, 1998 to 2021")
```
```{r}
library(fGarch)
library(lmtest)
library(hwwntest)
library(moments)
```

```{r}
skewness(Return)
kurtosis(Return)
```

```{r}
qqnorm(Return)
qqline(Return)
```

```{r}
modelma2<-arima(ts(Return),order=c(0,0,5),seasonal=list(order=c(0,0,1),period=12))
modelma2
```

```{r}
u<-resid(modelma2)
acf(resid(modelma2),36)
pacf(resid(modelma2),36)
spectrum(resid(modelma2),span=8)
bartlettB.test(resid(modelma2))
skewness(resid(modelma2))
kurtosis(resid(modelma2))
```

```{r}
u.ts<-ts(resid(modelma2))
modelgarch11<-garchFit(~garch(1,1),data=u.ts,trace=FALSE)
summary(modelgarch11)
```

```{r}
residsstdzd11<-residuals(modelgarch11,standard=TRUE)
plot(residsstdzd11,type='l')
skewness(residsstdzd)
kurtosis(residsstdzd)
```

```{r}
skewness(residsstdzd[-251])
kurtosis(residsstdzd[-251])
```

```{r}
bartlettB.test(residsstdzd)
```

